### PR TITLE
feat: add API to set time unit in a metric

### PR DESCRIPTION
**Pull request by SergeTupchiy**
Hi team,

This a small and backward-compatible extension to  allow reusing the same client for writing data to different tables with different time units.
Something similar to Go client: https://github.com/GreptimeTeam/greptimedb-client-go/blob/098f37980d47a1216de98643d658799bdd6df12b/docs/insert.md?plain=1#L84

### CODE REVIEW

**Comment by killme2008** [comment]
Thank u!  👍

**Review by killme2008 — APPROVED** [review]
LGTM

**Comment by killme2008** [comment]
@SergeTupchiy Thank you for your contribution. Could you please also update the README? Add the `timeunit` option to the `Usage` section.

**Comment by SergeTupchiy** [comment]
Thanks @killme2008, done: https://github.com/GreptimeTeam/greptimedb-client-erl/pull/36
Would it be possible to tag a new release?

**Comment by killme2008** [comment]
> Thanks @killme2008, done: #37 Would it be possible to tag a new release?

Of course, I released v0.1.7 https://github.com/GreptimeTeam/greptimedb-client-erl/releases/tag/v0.1.7

Thank u!

**Comment by SergeTupchiy** [comment]
Thank you very much @killme2008!

**Pull request merged**
